import { TAX_YEAR } from "@/lib/constants/tax-year";
import { getCountryConfig } from "@/lib/countries/registry";
import type { CountryCode } from "@/lib/countries/types";

// Country-specific descriptions for SEO
const COUNTRY_DESCRIPTIONS: Partial<Record<CountryCode, string>> = {
  US: `Free ${TAX_YEAR} take home pay calculator for all 50 US states + DC. Calculate your salary after taxes including federal, state, Social Security, Medicare, 401(k), HSA, and IRA deductions.`,
  CA: `Free 2026 take home pay calculator for Canada. Calculate your salary after federal and provincial or territorial income tax, taxable non-cash benefits, CPP/CPP2 or Quebec QPP/QPP2, EI, QPIP where applicable, RRSP, FHSA, RPP, union dues, childcare deductions, family credits, and charitable donation credits.`,
  MX: `Free 2026 take home pay calculator for Mexico. Calculate your salary after 2026 ISR income tax, employee IMSS, employment subsidy, aguinaldo, vacation premium and PTU exemptions, AFORE voluntary retirement, and personal deductions.`,
  SG: `Free ${TAX_YEAR} take home pay calculator for Singapore. Calculate your salary after income tax, age-based CPF, SRS, CPF top-ups, spouse, child, parent/grandparent, caregiver, disability, life insurance, donation, NSman, and Parenthood Tax Rebate inputs.`,
  KR: `Free ${TAX_YEAR} take home pay calculator for South Korea. Calculate your salary after income tax, local tax, national pension, health insurance, employment insurance, dependants, child deductions, non-taxable meal and childcare allowances, pension/IRP, insurance, medical, education, donation, rent credits, and the foreign employee flat-tax election.`,
  NL: `Free ${TAX_YEAR} take home pay calculator for the Netherlands. Calculate your salary after income tax, national insurance, employee pension premiums, self-paid lijfrente pension-account deductions using jaarruimte and reserveringsruimte, salary-norm-capped 30% ruling, general and labour tax credits, and IACK child credit eligibility.`,
  AU: `Free ${TAX_YEAR} take home pay calculator for Australia. Calculate your salary after taxes including income tax (Stage 3 cuts), Medicare levy, Medicare levy surcharge, Division 293 tax, LITO, employer Super Guarantee, optional concessional super contributions, work-related deductions, and DGR gifts or donations.`,
  NZ: `Free 2026/27 take home pay calculator for New Zealand. Calculate your salary after PAYE income tax, ACC earners levy, student loan repayments, KiwiSaver deductions, employer and government KiwiSaver context, Independent Earner Tax Credit, and payroll giving donation credits.`,
  OM: `Free 2026 take home pay calculator for Oman. Calculate employment salary after 0% 2026 personal income tax, expatriate or Omani worker treatment, selected monthly SPF insured wage, employee old-age/disability/death and employment-security contributions, employer non-Omani provident-scheme context, and optional SPF savings deposits.`,
  PT: `Free ${TAX_YEAR} take home pay calculator for Portugal. Calculate your salary after IRS income tax, Social Security contributions, IRS Jovem youth employment-income relief, NHR 2.0, PPR tax credits, dependent deductions, and solidarity surcharge.`,
  TH: `Free ${TAX_YEAR} take home pay calculator for Thailand. Calculate your salary after taxes including personal income tax (progressive rates 0-35%), Social Security Fund contributions, and Thai relief inputs like Provident Fund, RMF, SSF, and ESG funds.`,
  HK: `Free ${TAX_YEAR} take home pay calculator for Hong Kong. Calculate your salary after salaries tax, MPF contributions, employer-provided housing rental value, the 2025/26 one-off tax reduction, resident allowances, MPF TVC/QDAP, VHIS premiums, assisted reproductive service expenses, and common deductions.`,
  ID: `Free ${TAX_YEAR} take home pay calculator for Indonesia. Calculate salary after PPh 21 income tax, BPJS Kesehatan, JHT, JP, PTKP family status, DPLK pension, and approved zakat deductions.`,
  MY: `Free ${TAX_YEAR} take home pay calculator for Malaysia. Calculate your salary after individual income tax, EPF/KWSP, SOCSO, EIS, PRS, voluntary EPF, YA 2025 resident reliefs, approved donation deductions, and resident tax rebates.`,
  TW: `Free ${TAX_YEAR} take home pay calculator for Taiwan. Calculate resident or non-resident salary after comprehensive income tax, Labor Insurance, Employment Insurance, National Health Insurance, voluntary labor pension, exemptions, standard or itemized deductions, special deductions, basic living expense difference, and Employment Gold Card relief.`,
  UK: `Free ${TAX_YEAR} take home pay calculator for the United Kingdom. Calculate your salary after Income Tax with Personal Allowance taper, taxable benefits in kind, Class 1 National Insurance, Scottish Income Tax rates, student loan and postgraduate loan deductions, Marriage Allowance, and pension tax relief.`,
  DE: `Free ${TAX_YEAR} take home pay calculator for Germany. Calculate your salary after taxes including income tax (Einkommensteuer) per §32a EStG, Solidarity Surcharge (Solidaritätszuschlag), and social security contributions (pension, health, unemployment, and long-term care insurance).`,
  AE: `Free 2026 take home pay calculator for the United Arab Emirates. Calculate UAE salary after 0% personal income tax, monthly basic salary for ILOE unemployment insurance, employee-paid ILOE premiums, GPSSA contribution account salary, and modeled UAE national or GCC insurance extension employee pension contributions.`,
  AM: `Free 2026 take home pay calculator for Armenia. Calculate salary after the 20% employment income tax, funded pension social contribution, stamp duty, 2026 medical insurance charge, eligible mortgage-interest refunds, specialized higher-education tuition refunds, and SRC healthcare or education social-expense refunds.`,
  CN: `Free 2026 take home pay calculator for China. Calculate your salary after Individual Income Tax (IIT), taxable in-kind benefits, annual one-time bonus tax treatment, social insurance, housing fund contributions, special additional deductions or foreign individual allowance exemptions, individual pension, enterprise annuity, tax-preferred health insurance, and charity deductions.`,
  CZ: `Free 2026 take home pay calculator for Czechia. Calculate employment salary after Czech income tax, taxable non-cash benefits, company-car private-use valuation, employee social security, health insurance, taxpayer, spouse, child, disability and ZTP/P credits, retirement-product deductions, and charitable gifts.`,
  JP: `Free 2026 take home pay calculator for Japan. Calculate your salary after NTA employment income deduction, 2025+ basic deduction, spouse and dependent deductions, iDeCo pension contributions, life-insurance, earthquake-insurance, medical-expense and donation deductions including furusato nozei resident-tax credits, national income tax, reconstruction surtax, resident tax, and social insurance.`,
  IN: `Free 2026 take home pay calculator for India. Calculate salary after new or old regime income tax, Section 87A rebate with marginal relief, surcharge, 4% health and education cess, EPF, HRA exemption, professional tax, Section 80C, NPS 80CCD(1B), and Section 80D medical insurance inputs.`,
  PH: `Free 2026 take home pay calculator for the Philippines. Calculate your salary after compensation income tax, SSS, PhilHealth, Pag-IBIG, the 13th month/other benefits exclusion, BIR RR 29-2025 de minimis benefit ceilings, and non-resident gross tax treatment when selected.`,
  VN: `Free 2026 take home pay calculator for Vietnam. Calculate resident or non-resident salary after the 2026 PIT law, updated personal and dependent deductions, social insurance, health insurance, foreign-worker unemployment insurance treatment, voluntary pension deductions, and approved charitable or humanitarian contributions.`,
  KH: `Free 2026 take home pay calculator for Cambodia. Calculate resident or non-resident salary after GDT tax on salary, spouse and child allowances, taxable fringe benefits, and employee NSSF health and pension contributions.`,
  LK: `Free 2026 take home pay calculator for Sri Lanka. Calculate your salary after APIT income tax, employee EPF deductions, secondary-employment Table 07, remote foreign-employer Table 08, annual lump-sum payments, taxable in-kind or non-cash benefits, Table 03 terminal benefits, modeled reliefs, and employer EPF/ETF cost context.`,
  FR: `Free 2026 take home pay calculator for France. Calculate your salary after the 2026 French income-tax scale, employee social contributions, taxable benefits in kind, family quotient cap, decote, 10% or actual professional expenses, PER retirement savings, charitable donation reductions, and the impatriate salary-premium regime when selected.`,
  GE: `Free 2026 take home pay calculator for Georgia. Calculate employment salary after 20% income tax and funded pension contributions, or model individual entrepreneur small business status at 1%/3% turnover tax and micro business status up to the official gross-income limit.`,
  IT: `Free 2026 take home pay calculator for Italy. Calculate your salary after IRPEF, employee INPS social security, taxable fringe benefits, the post-2024 impatriate-worker regime, Article 13 employment tax credits, Article 12 spouse, child, and ascendant credits, supplementary pension deductions, and regional or municipal add-ons.`,
  IE: `Free 2026 take home pay calculator for Ireland. Calculate your salary after PAYE income tax, Class A PRSI, Universal Social Charge, taxable benefit-in-kind, SARP inbound assignee relief, Revenue pension relief, MyFutureFund, rent tax credit, health expense relief, and family tax credits.`,
  IS: `Free 2026 take home pay calculator for Iceland. Calculate your salary after Iceland withholding tax, personal tax credit, mandatory employee pension, optional private supplementary pension savings, and approved foreign expert relief when selected.`,
  GR: `Free 2026 take home pay calculator for Greece. Calculate employment salary after Greek income tax, taxable benefits in kind, age and dependent-child rate adjustments, e-EFKA employee contributions, occupational pension deductions, and Article 5C new-tax-resident relief when selected.`,
  NO: `Free 2026 take home pay calculator for Norway. Calculate salary after ordinary Norwegian income tax, bracket tax, National Insurance, IPS pension savings, union dues, childcare, commuting, debt-interest deductions, or the PAYE flat-tax scheme for eligible foreign workers when selected.`,
  DK: `Free 2026 take home pay calculator for Denmark. Calculate your salary after AM-bidrag, Danish income tax, average municipal tax, taxable benefits in kind, employment and job allowances, rate pension deductions, union/A-kasse fees, commuting, household services, documented work expenses, and the researcher/highly paid employee scheme when selected.`,
  FI: `Free 2026 take home pay calculator for Finland. Calculate your salary after state and municipal income tax assumptions, taxable fringe benefits, age-sensitive employee pension/unemployment/health contributions, commuting deductions, unemployment fund fees, income-production expenses, household expense credit, voluntary pension/PS savings deficit credit, and the foreign key employee tax-at-source regime when selected.`,
  SE: `Free 2026 take home pay calculator for Sweden. Calculate your salary after municipal and state income tax assumptions, general pension contribution, private pension savings when no occupational pension exists, commuting and work-expense deductions, ROT/RUT and green-technology reductions, and expert tax relief when selected.`,
  ES: `Free 2026 take home pay calculator for Spain. Calculate salary after IRPF resident tax, IRNR non-resident tax, employee Social Security, regional scales, family minimums, pension contribution reductions, and the Article 93 / Beckham-law regime when selected.`,
  BM: `Free 2026/27 take home pay calculator for Bermuda. Calculate your salary after employee payroll tax on cash or in-kind benefits, optional employee payroll-tax deduction treatment, covered employee social insurance, occupational pension contributions, and capped health-insurance payroll deductions.`,
  QA: `Free 2026 take home pay calculator for Qatar. Calculate salary after 0% employment income tax, expatriate no-deduction treatment, or Qatari/GCC pension-covered employee social insurance at 7% on GRSIA basic salary, social allowance, and capped housing allowance components.`,
  AT: `Free 2026 take home pay calculator for Austria. Calculate your salary after the 2026 wage-tax tariff, employee social insurance, 13th/14th salary special-payment taxation, taxable in-kind benefits, transportation credit, Pendlerpauschale, Pendlereuro, Family Bonus Plus, church contributions, donations, and voluntary statutory pension deductions.`,
  BE: `Free 2026 take home pay calculator for Belgium. Calculate your salary after federal personal income tax, employee social security, taxable benefits in kind, personal tax-free allowance, dependent-child increases, pension savings, childcare and gift tax reductions, professional expenses, special inpatriate regime allowance, and municipal surcharge proxy.`,
  CY: `Free 2026 take home pay calculator for Cyprus. Calculate employment salary after Cyprus income tax, Social Insurance, GHS, approved pension, provident, or medical-fund deductions, resident TD59 reliefs, and Article 8 first-employment exemptions when selected.`,
  ZA: `Free 2026/27 take home pay calculator for South Africa. Calculate your salary after SARS PAYE income tax, taxable fringe benefits, UIF, retirement fund deductions, age rebates, medical tax credits, additional medical expenses credit, and Section 18A donations.`,
  KE: `Free 2026 take home pay calculator for Kenya. Calculate your salary after KRA PAYE, taxable non-cash benefits, NSSF, SHIF, Affordable Housing Levy, personal relief, registered pension deductions, post-retirement medical fund deductions, mortgage interest, insurance relief, and PWD exemption.`,
  CO: `Free 2026 take home pay calculator for Colombia. Calculate your salary after Colombian resident income tax, employee health and pension contributions, pension solidarity fund, dependents, prepaid health, housing interest, voluntary pension or AFC savings, and electronic-invoice deductions.`,
  BB: `Free 2026 take home pay calculator for Barbados. Calculate your salary after BRA personal income tax, employee National Insurance, the Resilience and Regeneration Fund contribution, spouse and pensioner allowances, medical exam relief, union dues, charity deductions, and renewable energy deductions.`,
  BR: `Free 2026 take home pay calculator for Brazil. Calculate salary after Receita Federal IRPF, employee INSS, 13th salary IRRF, dependents, PGBL private pension deductions, education caps, medical deductions, and the simplified annual discount.`,
  PY: `Free 2026 take home pay calculator for Paraguay. Calculate your salary after DNIT IRP-RSP personal income tax, IPS employee contributions, legal aguinaldo treatment, and modeled documented personal and family expense deductions.`,
  BZ: `Free 2026 take home pay calculator for Belize. Calculate your salary after BTS employee income tax, current personal relief amendments, Social Security Board weekly insurable earnings and age exceptions, charitable relief, and education relief for eligible non-dependent children.`,
  PA: `Free 2026 take home pay calculator for Panama. Calculate Panama-source salary after income tax, employee social security, educational insurance, married exemption, mortgage interest, education and medical deductions, charity deductions, and approved retirement fund contributions capped at the lower of 10% of annual gross income or USD 15,000.`,
  CR: `Free 2026 take home pay calculator for Costa Rica. Calculate your salary after Hacienda salary tax, CCSS employee contributions, legal aguinaldo treatment, spouse and child tax credits, and voluntary complementary pension contributions.`,
  EC: `Free 2026 take home pay calculator for Ecuador. Calculate your salary after SRI income tax, IESS employee contributions, older-adult or disability/sustituto income exemptions, and the 2026 personal-expense rebate with family-dependent and disability/catastrophic caps.`,
  SV: `Free 2026 take home pay calculator for El Salvador. Calculate your salary after income tax, ISSS, AFP pension contributions, voluntary AFP deductions, and medical and education expense deductions.`,
  PE: `Free 2026 take home pay calculator for Peru. Calculate fifth-category salary after SUNAT income tax, the 7 UIT deduction, statutory July/December gratifications, EsSalud or EPS gratification bonus, ONP or AFP pension withholding, and the additional 3 UIT deductible expense option.`,
  GT: `Free 2026 take home pay calculator for Guatemala. Calculate salaried employment income after SAT ISR, IGSS, the Q48,000 personal deduction, VAT invoice credit, verified donations, and death-risk life insurance premiums.`,
  DO: `Free 2026 take home pay calculator for the Dominican Republic. Calculate salary after DGII ISR, SDSS payroll coverage, monthly AFP/SFS contribution salary, TSS caps, legal Christmas salary treatment, employee-taxable fringe benefits when applicable, and Law 179-09 education expense deductions.`,
  UY: `Free 2026 take home pay calculator for Uruguay. Calculate salary after IRPF, BPS pension, FONASA, labor reconversion fund, sueldo anual complementario treatment, child deduction credits, voluntary AFAP savings, and rent or mortgage housing credits.`,
  CL: `Free 2026 take home pay calculator for Chile. Calculate salary after SII second-category tax, AFP pension, 7% health, additional Isapre premium, contract-specific unemployment insurance, and APV regime A or B retirement savings.`,
  RO: `Free 2026 take home pay calculator for Romania. Calculate salary after flat income tax, CAS, CASS, Article 77 personal deductions, dependent-count phase-outs, under-26 and school-child deductions, voluntary pension deductions, and voluntary health insurance or private healthcare subscription deductions.`,
  AD: `Free 2026 take home pay calculator for Andorra. Calculate resident employment salary after IRPF, employee CASS, employment expense deduction, family and disability relief, mortgage relief, and qualifying pension-plan deductions.`,
  AL: `Free 2026 take home pay calculator for Albania. Calculate salary after personal income tax, taxable benefits in kind, employee social and health insurance, employment allowance treatment, DIVA child and education deductions, and voluntary pension deductions.`,
  BA: `Free 2026 take home pay calculator for Bosnia and Herzegovina. Calculate salary after FBiH, Republika Srpska, or Brcko income tax, employee contributions, dependent allowances, disability deductions, mortgage interest, life insurance, education costs, and entity-specific voluntary deductions.`,
  BG: `Free 2026 take home pay calculator for Bulgaria. Calculate salary in euros after flat personal income tax, employee social and health insurance, child, disabled-child, personal reduced-working-capacity, voluntary pension or insurance, and approved donation tax reliefs.`,
  BH: `Free 2026 take home pay calculator for Bahrain. Calculate ordinary employment salary after 0% personal income tax, expatriate or Bahraini worker treatment, SIO basic wage and recurring allowance components, the BHD 4,000 monthly contribution cap, 1% unemployment insurance, and Bahraini employee pension insurance contributions.`,
  BS: `Free 2026 take home pay calculator for The Bahamas. Calculate ordinary employment salary after 0% personal income tax, National Insurance category, selected weekly NIB basic wage, formal tips or gratuities, the BSD 810 weekly ceiling, standard or age-65-plus employee NIB rates, and employer-only Retirement Benefit or summer-employment categories.`,
  CH: `Free 2026 take home pay calculator for Switzerland. Calculate Zurich benchmark salary after federal, cantonal and communal income tax, AHV/IV/EO, ALV, accident insurance, occupational pension, Pillar 3a, child, insurance, childcare, training, and donation deductions.`,
  CW: `Free 2026 take home pay calculator for Curacao. Calculate resident or foreign-taxpayer salary after Curacao income tax, resident wage-tax credits, single-earner, child and elderly allowances, AOV/AWW, BVZ, AVBZ premiums, and modeled savings or provident-fund deductions.`,
  EE: `Free 2026 take home pay calculator for Estonia. Calculate salary after income tax, general or pensionable-age basic exemption, unemployment insurance, second-pillar pension rates, and third-pillar pension deductions.`,
  EG: `Free 2026 take home pay calculator for Egypt. Calculate salary after employee social insurance coverage, the 2026 NOSI monthly salary floor and ceiling, taxable employment benefits, salary tax brackets, high-income band phase-out, and private pension or life/health insurance premium deductions.`,
  HR: `Free 2026 take home pay calculator for Croatia. Calculate ordinary Croatian payroll salary after employee pension contributions, taxable benefits in kind, local income tax rates, youth income-tax relief, Croatian returnee relief, resident spouse and child allowances, employer health insurance context, or the qualifying foreign-employer digital-nomad scenario when selected.`,
  HU: `Free 2026 take home pay calculator for Hungary. Calculate salary after flat personal income tax, employee social security, NAV mother and under-25 PIT base allowances, personal and first-marriage allowances, family tax and contribution allowances, and voluntary pension fund tax credits.`,
  IL: `Free 2026 take home pay calculator for Israel. Calculate salary after income tax, resident and additional credit points, National Insurance, health insurance, employee pension, pension tax credits, and Keren Hishtalmut study fund contributions.`,
  JO: `Free 2026 take home pay calculator for Jordan. Calculate salary after PIT, national contribution tax, Social Security, resident-dependant exemptions, personal expenses, and government or approved charity donation deductions.`,
  KW: `Free 2026 take home pay calculator for Kuwait. Calculate ordinary employment salary after 0% personal income tax, expatriate or Kuwaiti worker treatment, PIFSS basic and supplementary insurance salaries, pension-increase contribution, private/oil-sector unemployment insurance, and conditional financial-remuneration contribution.`,
  LT: `Free 2026 take home pay calculator for Lithuania. Calculate salary after VMI PIT brackets, ordinary or disability NPD, state social insurance, health insurance, optional second-pillar pension accumulation, and Article 21 deductions for additional pension, grandfathered life or III-pillar premiums, and formal study costs.`,
  LU: `Free 2026 take home pay calculator for Luxembourg. Calculate salary after class 1, class 1a, or class 2 income tax, employment fund surcharge, social-security contributions, employee credits, child/age tax-class selection, single-parent tax credit, and private pension deductions.`,
  LV: `Free 2026 take home pay calculator for Latvia. Calculate salary after PIT, general or pensioner non-taxable minimum, dependant allowances, social insurance, private pension or life insurance, and eligible expense deductions.`,
  MA: `Free 2026 take home pay calculator for Morocco. Calculate salary after income tax, CNSS, AMO, contribution wage-base caps, professional expense deduction, family charge reductions, first-employment IR exemption, mortgage interest, charitable contributions, and pension insurance deductions.`,
  MT: `Free 2026 take home pay calculator for Malta. Calculate ordinary Malta employment salary after MTCA tax bands, Class 1 SSC, PRS and occupational pension credits, qualifying fee deductions, Nomad Residence Permit authorised-work tax scenarios, or the Highly Skilled Individuals 15% employment-income regime when selected.`,
  MU: `Free 2025/26 take home pay calculator for Mauritius. Calculate salary after MRA PAYE bands, CSG, dependent deductions, pension, medical insurance, charity, school fee, tertiary education, carer wage, housing, and green investment reliefs.`,
  PL: `Free 2026 take home pay calculator for Poland. Calculate salary after PIT, ZUS, health insurance, PIT-0 reliefs for under-26, return, family 4+, or working-senior eligibility, PPK employee contributions, child tax relief, standard employee costs, IKZE, PIT/O donations, and internet relief.`,
  ME: `Free 2026 take home pay calculator for Montenegro. Calculate payroll salary after PIT, taxable benefits in kind, pension and unemployment contributions, municipality surtax context, or qualifying digital-nomad foreign-source income with no Montenegro salary tax or employee social contribution deduction.`,
  RS: `Free 2026 take home pay calculator for Serbia. Calculate salary after flat salary tax, taxable fringe benefits, non-taxable salary amount, employee pension, health, and unemployment contributions, newly settled taxpayer relief, plus the supplementary annual personal income tax estimate with under-40, dependant, and investment-fund credit inputs.`,
  RW: `Free 2026 take home pay calculator for Rwanda. Calculate salary after PAYE, taxable benefits in kind, RSSB pension or voluntary-member pension coverage, maternity leave contribution, optional RSSB medical scheme coverage, and CBHI health contribution.`,
  SA: `Free 2026 take home pay calculator for Saudi Arabia. Calculate expatriate or Saudi employment salary after 0% personal income tax, existing-system or 2026 new-system Saudi employee GOSI annuities, SANED unemployment insurance, and a GOSI wage base built from basic wage plus cash or in-kind housing allowance.`,
  SC: `Free 2026 take home pay calculator for Seychelles. Calculate salary after SRC citizen, non-citizen, specific-project, or stevedore employment income tax, employee Seychelles Pension Fund contributions, optional SPF voluntary salary deductions, and a separate employer-only non-monetary benefits tax estimate.`,
  SI: `Free 2026 take home pay calculator for Slovenia. Calculate salary after PIT, general and low-income allowances, employee social security, long-term care, compulsory health contribution, dependent and personal allowances, supplementary pension deductions, and tax-exempt meal, commute, and holiday allowances.`,
  TR: `Free 2026 take home pay calculator for Turkey. Calculate salary after GIB wage tax brackets, SSI, unemployment insurance, stamp tax, minimum-wage exemptions, disability allowance, insurance premiums, union dues, education and health expense deductions, and donation relief.`,
};

// Country-specific keywords for SEO
const COUNTRY_KEYWORDS: Partial<Record<CountryCode, string[]>> = {
  US: [
    "us take home pay calculator",
    "usa salary after tax",
    "american paycheck calculator",
    `${TAX_YEAR} federal tax calculator`,
    "state tax calculator",
    "401k tax savings",
    "california paycheck calculator",
    "new york salary calculator",
    "texas take home pay",
  ],
  CA: [
    "canada take home pay calculator",
    "canada salary after tax",
    "2026 canada tax calculator",
    "canadian payroll calculator",
    "ontario salary after tax",
    "cpp ei calculator",
    "canada taxable benefits calculator",
    "rrsp tax deduction calculator",
    "canada charitable donation tax credit",
    "canada childcare deduction calculator",
    "canada paycheck calculator",
  ],
  MX: [
    "mexico take home pay calculator",
    "mexico salary after tax",
    "2026 mexico tax calculator",
    "mexico isr calculator",
    "mexican payroll calculator",
    "salario neto mexico",
    "calculadora isr mexico",
    "aportaciones voluntarias retiro mexico",
    "subsidio para el empleo 2026",
    "aguinaldo exento ISR",
    "prima vacacional exenta",
    "PTU exenta ISR",
  ],
  AU: [
    "australia take home pay calculator",
    "australian salary after tax",
    `${TAX_YEAR} australia tax calculator`,
    "ato tax calculator",
    "medicare levy calculator",
    "superannuation calculator",
    "salary sacrifice super calculator",
    "concessional super contributions cap",
    "stage 3 tax cuts calculator",
    "lito calculator",
    "division 293 tax calculator",
    "high income super tax",
    "australia work related deduction calculator",
    "ato gifts donations deduction",
    "dgr donation tax deduction australia",
  ],
  NZ: [
    "new zealand take home pay calculator",
    "new zealand salary after tax",
    "nz paye calculator",
    "nz salary calculator",
    "2026 nz tax calculator",
    "new zealand paycheck calculator",
    "acc earners levy calculator",
    "kiwisaver deduction calculator",
    "student loan repayment nz",
    "independent earner tax credit calculator",
  ],
  OM: [
    "oman take home pay calculator",
    "oman salary after tax",
    "2026 oman payroll calculator",
    "oman personal income tax 2028",
    "oman social protection fund calculator",
    "oman SPF employee contribution",
    "oman provident scheme calculator",
    "oman optional SPF savings",
    "oman expatriate salary calculator",
    "oman Omani employee social protection",
  ],
  NL: [
    "netherlands take home pay calculator",
    "dutch salary after tax",
    `${TAX_YEAR} netherlands tax calculator`,
    "30 percent ruling calculator",
    "netherlands 30 percent ruling salary norm",
    "netherlands IACK calculator",
    "dutch income tax calculator",
    "loonbelasting calculator",
    "netherlands employee pension premium tax",
    "dutch pension premium payroll deduction",
    "netherlands lijfrente deduction calculator",
    "dutch jaarruimte calculator",
    "netherlands reserveringsruimte pension",
  ],
  PT: [
    "portugal take home pay calculator",
    "portuguese salary after tax",
    `${TAX_YEAR} portugal tax calculator`,
    "irs portugal calculator",
    "seguranca social calculator",
    "portugal income tax calculator",
    "portugal paycheck calculator",
    "portugal IRS Jovem calculator",
    "portugal youth tax relief",
    "portugal NHR 2.0 calculator",
    "portugal PPR tax credit",
  ],
  SG: [
    "singapore take home pay calculator",
    "sg salary after tax",
    `${TAX_YEAR} singapore tax calculator`,
    "cpf contribution calculator",
    "singapore income tax",
    "srs contribution calculator",
    "singapore personal relief cap",
    "singapore spouse parent relief calculator",
  ],
  KR: [
    "korea take home pay calculator",
    "korean salary after tax",
    `${TAX_YEAR} korea tax calculator`,
    "korean income tax calculator",
    "national pension korea",
    "4 major insurance korea",
    "korea rent tax credit calculator",
    "korea year end tax settlement",
    "korea pension IRP tax credit",
    "korea foreign worker flat tax",
  ],
  KW: [
    "kuwait take home pay calculator",
    "kuwait salary after tax",
    "2026 kuwait payroll calculator",
    "kuwait no personal income tax",
    "kuwait PIFSS calculator",
    "kuwait employee social security contribution",
    "kuwait basic supplementary PIFSS salary",
    "kuwait PIFSS pension increase contribution",
    "kuwait unemployment insurance contribution",
    "kuwait expatriate salary calculator",
    "kuwaiti employee PIFSS contribution",
  ],
  TH: [
    "thailand take home pay calculator",
    "thai salary after tax",
    `${TAX_YEAR} thailand tax calculator`,
    "thai income tax calculator",
    "personal income tax thailand",
    "social security thailand",
    "provident fund thailand",
    "rmf thailand calculator",
    "ssf thailand calculator",
    "thailand paycheck calculator",
    "rd go th tax calculator",
    "thai revenue department tax",
  ],
  HK: [
    "hong kong take home pay calculator",
    "hong kong salary after tax",
    `${TAX_YEAR} hong kong tax calculator`,
    "hong kong salaries tax calculator",
    "mpf contribution calculator",
    "hong kong payroll tax",
    "hong kong vhis tax deduction",
    "hong kong qdap mpf tvc calculator",
    "hong kong housing benefit rental value",
    "hong kong parent grandparent allowance",
  ],
  ID: [
    "indonesia take home pay calculator",
    "indonesian salary after tax",
    `${TAX_YEAR} indonesia tax calculator`,
    "pph 21 calculator",
    "indonesia income tax calculator",
    "bpjs calculator",
    "bpjs kesehatan",
    "bpjs ketenagakerjaan",
    "indonesia paycheck calculator",
    "indonesia dplk deduction",
    "indonesia zakat pph 21 deduction",
    "gaji bersih indonesia",
    "kalkulator pph 21",
    "tarif pph 21",
  ],
  MY: [
    "malaysia take home pay calculator",
    "malaysia salary after tax",
    `${TAX_YEAR} malaysia tax calculator`,
    "malaysia income tax calculator",
    "lhdn tax calculator",
    "hasil tax calculator",
    "epf contribution calculator",
    "kwsp contribution calculator",
    "socso calculator",
    "eis calculator malaysia",
    "malaysia paycheck calculator",
    "gaji bersih malaysia",
    "malaysia tax relief 2025",
    "malaysia zakat rebate",
    "malaysia prs relief",
    "malaysia sspn tax relief",
  ],
  TW: [
    "taiwan take home pay calculator",
    "taiwan salary after tax",
    `${TAX_YEAR} taiwan tax calculator`,
    "taiwan income tax calculator",
    "taiwan paycheck calculator",
    "labor insurance taiwan",
    "national health insurance taiwan",
    "taiwan comprehensive income tax",
    "taiwan tax brackets",
    "taiwan social insurance",
    "taiwan standard deduction calculator",
    "taiwan itemized deductions calculator",
    "taiwan employment gold card tax",
    "taiwan basic living expense deduction",
    "taiwan 綜合所得稅",
    "台灣薪資計算",
  ],
  UK: [
    "uk take home pay calculator",
    "united kingdom salary after tax",
    `${TAX_YEAR} uk tax calculator`,
    "hmrc tax calculator",
    "income tax calculator uk",
    "national insurance calculator",
    "scottish income tax calculator",
    "uk paycheck calculator",
    "salary calculator uk",
    "paye calculator",
    "personal allowance taper",
    "uk student loan repayment calculator",
    "uk benefits in kind tax calculator",
    "hmrc taxable benefits in kind",
    "postgraduate loan deduction calculator",
    "marriage allowance calculator",
    "uk pension tax relief calculator",
    "uk tax bands",
    "england tax calculator",
    "wales tax calculator",
    "northern ireland tax",
  ],
  DE: [
    "germany take home pay calculator",
    "german salary after tax",
    `${TAX_YEAR} germany tax calculator`,
    "germany income tax calculator",
    "einkommensteuer calculator",
    "solidaritätszuschlag calculator",
    "lohnsteuer calculator",
    "brutto netto rechner",
    "gehaltsrechner deutschland",
    "sozialversicherung beiträge",
    "krankenversicherung rechner",
    "rentenversicherung beitrag",
  ],
  AE: [
    "uae take home pay calculator",
    "dubai salary after tax",
    "abu dhabi salary calculator",
    "2026 uae salary calculator",
    "uae personal income tax",
    "gpssa contribution calculator",
    "uae contribution account salary",
    "uae ILOE basic salary premium",
    "emirati pension contribution",
    "gcc pension uae",
    "uae unemployment insurance premium",
    "iloe deduction calculator",
    "uae expat salary calculator",
  ],
  AM: [
    "armenia take home pay calculator",
    "armenia salary after tax",
    "2026 armenia tax calculator",
    "armenia income tax calculator",
    "armenia funded pension contribution",
    "armenia stamp duty salary",
    "armenia mortgage interest income tax refund",
    "armenia social expenses refund",
    "armenia healthcare education tax refund",
  ],
  CN: [
    "china take home pay calculator",
    "china salary after tax",
    "2026 china tax calculator",
    "china iit calculator",
    "individual income tax china",
    "china social insurance calculator",
    "中国税后工资计算器",
    "china housing fund calculator",
    "china annual bonus tax calculator",
    "china year end bonus iit",
    "china five insurance one fund",
    "china foreign allowance exemption",
    "china taxable in kind benefits",
    "五险一金计算器",
  ],
  CZ: [
    "czechia take home pay calculator",
    "czech republic salary after tax",
    "2026 czech tax calculator",
    "czech payroll calculator",
    "czech social security calculator",
    "czech health insurance salary",
    "czech taxable benefits calculator",
    "czech company car benefit tax",
    "czech child tax credit",
    "czech spouse tax credit",
    "czech disability tax credit",
    "czech ZTP/P tax credit",
  ],
  JP: [
    "japan take home pay calculator",
    "japan salary after tax",
    "2026 japan tax calculator",
    "japanese income tax calculator",
    "japan resident tax calculator",
    "japan social insurance calculator",
    "japan pension calculator",
    "japan ideco tax deduction calculator",
    "japan life insurance deduction calculator",
    "japan medical expense deduction calculator",
    "japan spouse dependent deduction calculator",
    "shakai hoken calculator",
    "japan payroll calculator",
    "給与計算 手取り",
  ],
  IN: [
    "india take home pay calculator",
    "india salary after tax",
    "2026 india tax calculator",
    "india income tax calculator",
    "new tax regime calculator",
    "old tax regime 80C calculator",
    "india NPS 80CCD 1B deduction calculator",
    "india HRA exemption calculator",
    "india section 80D health insurance deduction calculator",
    "india professional tax deduction calculator",
    "india epf calculator",
    "section 87a rebate calculator",
    "india cess calculator",
    "indian payroll calculator",
    "भारत टैक्स कैलकुलेटर",
    "income tax slabs 2026",
  ],
  PH: [
    "philippines take home pay calculator",
    "philippines salary after tax",
    "2026 philippines tax calculator",
    "philippine income tax calculator",
    "train law tax calculator",
    "philippines sss calculator",
    "philhealth contribution calculator",
    "pag ibig calculator",
    "philippines 13th month tax exempt calculator",
    "philippines de minimis benefits calculator",
    "philippines non resident alien tax calculator",
    "philippines payroll calculator",
    "sweldo calculator philippines",
  ],
  VN: [
    "vietnam take home pay calculator",
    "vietnam salary after tax",
    "2026 vietnam tax calculator",
    "vietnam income tax calculator",
    "vietnam social insurance calculator",
    "vietnam 2026 personal income tax law",
    "vietnam foreign employee unemployment insurance",
    "vietnam non resident PIT calculator",
    "vietnam voluntary pension tax deduction",
    "vietnam charitable donation PIT deduction",
    "vietnam humanitarian contribution deduction",
    "thuế thu nhập cá nhân",
    "lương gross sang net",
    "vietnam payroll calculator",
    "bảo hiểm xã hội calculator",
    "tính lương sau thuế",
  ],
  KH: [
    "cambodia take home pay calculator",
    "cambodia salary after tax",
    "2026 cambodia tax on salary calculator",
    "cambodia non resident salary tax",
    "cambodia fringe benefit tax",
    "cambodia NSSF contribution calculator",
    "cambodia dependent spouse allowance",
    "cambodia child allowance salary tax",
  ],
  LK: [
    "sri lanka take home pay calculator",
    "sri lanka salary after tax",
    "2026 sri lanka tax calculator",
    "sri lanka APIT calculator",
    "sri lanka EPF calculator",
    "sri lanka ETF employer contribution",
    "sri lanka secondary employment tax",
    "sri lanka lump sum APIT tax",
    "sri lanka non cash benefits tax",
    "remote foreign employer sri lanka tax",
    "sri lanka PAYE calculator",
    "sri lanka income tax calculator",
  ],
  FR: [
    "france take home pay calculator",
    "france salary after tax",
    "2026 france tax calculator",
    "french payroll calculator",
    "salaire net france",
    "france family quotient calculator",
    "france PER retirement savings deduction",
    "france frais reels calculator",
    "france impatriate regime calculator",
    "france impatriation premium calculator",
    "france taxable benefits in kind calculator",
  ],
  GE: [
    "georgia take home pay calculator",
    "georgia salary after tax",
    "2026 georgia tax calculator",
    "georgia income tax calculator",
    "georgia pension contribution calculator",
    "georgia individual entrepreneur tax calculator",
    "georgia small business status tax",
    "georgia 1 percent tax calculator",
    "georgia micro business tax",
    "georgia digital nomad tax calculator",
  ],
  IT: [
    "italy take home pay calculator",
    "italy salary after tax",
    "2026 italy tax calculator",
    "italian payroll calculator",
    "stipendio netto italia",
    "italy family tax credit calculator",
    "italy spouse dependent deduction",
    "italy supplementary pension deduction",
    "italy impatriate regime calculator",
    "italy taxable fringe benefits calculator",
  ],
  IE: [
    "ireland take home pay calculator",
    "ireland salary after tax",
    "2026 ireland tax calculator",
    "irish PAYE calculator",
    "USC PRSI calculator",
    "ireland pension relief calculator",
    "MyFutureFund take home pay",
    "ireland rent tax credit calculator",
    "ireland SARP calculator",
    "ireland special assignee relief programme",
    "ireland benefit in kind PAYE calculator",
  ],
  IS: [
    "iceland take home pay calculator",
    "iceland salary after tax",
    "2026 iceland tax calculator",
    "iceland payroll calculator",
    "iceland pension contribution calculator",
    "iceland private pension savings tax deduction",
    "iceland foreign expert tax relief",
    "skatturinn tax calculator",
  ],
  NO: [
    "norway take home pay calculator",
    "norway salary after tax",
    "2026 norway tax calculator",
    "norway PAYE foreign workers calculator",
    "norway kildeskatt pa lonn calculator",
    "norway IPS pension deduction",
    "norway union dues deduction",
    "norway childcare deduction",
    "norway commuting deduction",
    "norway debt interest deduction",
    "skatteetaten PAYE calculator",
  ],
  GR: [
    "greece take home pay calculator",
    "greece salary after tax",
    "2026 greece tax calculator",
    "greece article 5C tax relief",
    "greece 50 percent tax exemption",
    "greece e-EFKA salary calculator",
    "greece occupational pension deduction",
    "greece taxable benefits in kind salary",
  ],
  DK: [
    "denmark take home pay calculator",
    "denmark salary after tax",
    "2026 denmark tax calculator",
    "danish payroll calculator",
    "denmark researcher tax scheme calculator",
    "denmark highly paid employee tax",
    "denmark rate pension deduction",
    "denmark commuting deduction",
    "denmark union fee deduction",
    "denmark household services deduction",
    "denmark taxable benefits in kind",
  ],
  FI: [
    "finland take home pay calculator",
    "finland salary after tax",
    "2026 finland tax calculator",
    "finnish payroll calculator",
    "finland key employee tax calculator",
    "vero tax at source calculator",
    "finland commuting deduction",
    "finland taxable fringe benefits calculator",
    "finland unemployment fund fee deduction",
    "finland income production expenses deduction",
    "finland household expense credit",
    "finland voluntary pension deduction",
  ],
  SE: [
    "sweden take home pay calculator",
    "sweden salary after tax",
    "2026 sweden tax calculator",
    "swedish payroll calculator",
    "sweden expert tax relief calculator",
    "forskarskattenamnden tax relief",
    "sweden private pension deduction",
    "sweden rot rut tax reduction",
    "sweden commuting deduction",
    "sweden green technology tax reduction",
  ],
  ES: [
    "spain take home pay calculator",
    "spain salary after tax",
    "2026 spain tax calculator",
    "spanish payroll calculator",
    "spain beckham law calculator",
    "spain article 93 tax calculator",
    "spain irpf calculator",
    "spain social security calculator",
  ],
  BM: [
    "bermuda take home pay calculator",
    "bermuda salary after tax",
    "2026 bermuda payroll tax calculator",
    "bermuda employee payroll tax",
    "bermuda taxable remuneration benefits in kind",
    "bermuda social insurance contribution",
    "bermuda occupational pension contribution",
    "bermuda health insurance payroll deduction",
    "bermuda net salary calculator",
  ],
  QA: [
    "qatar take home pay calculator",
    "qatar salary after tax",
    "2026 qatar payroll calculator",
    "qatar no income tax salary",
    "qatar social insurance contribution",
    "qatar grsia basic salary social allowance housing allowance",
    "qatar pension contribution calculator",
    "qatar expat salary calculator",
  ],
  AT: [
    "austria take home pay calculator",
    "austria salary after tax",
    "2026 austria tax calculator",
    "austrian payroll calculator",
    "lohnsteuer austria calculator",
    "austria 13th 14th salary calculator",
    "austria special payments tax calculator",
    "austria pendlerpauschale calculator",
    "austria family bonus plus calculator",
    "austria single earner tax credit",
    "austria church contribution deduction",
    "austria donation deduction",
    "austria taxable in kind benefits calculator",
  ],
  BE: [
    "belgium take home pay calculator",
    "belgium salary after tax",
    "2026 belgium tax calculator",
    "belgian payroll calculator",
    "ONSS RSZ calculator",
    "belgium tax free allowance calculator",
    "belgium dependent children tax calculator",
    "belgium pension savings tax reduction",
    "belgium childcare tax reduction",
    "belgium donation tax reduction",
    "belgium expat tax regime calculator",
    "belgium inpatriate taxpayer calculator",
    "belgium benefits in kind tax calculator",
  ],
  CY: [
    "cyprus take home pay calculator",
    "cyprus salary after tax",
    "2026 cyprus tax calculator",
    "cyprus payroll calculator",
    "cyprus social insurance calculator",
    "cyprus GHS contribution calculator",
    "cyprus first employment exemption calculator",
    "cyprus article 8 23A exemption",
    "cyprus article 8 21A exemption",
    "cyprus provident fund deduction",
    "cyprus medical fund deduction",
  ],
  ZA: [
    "south africa take home pay calculator",
    "south africa salary after tax",
    "2026 south africa tax calculator",
    "sars paye calculator",
    "south africa UIF calculator",
    "south africa retirement annuity deduction",
    "sars medical tax credit calculator",
    "section 18A donations tax deduction",
    "south africa taxable fringe benefits PAYE",
  ],
  KE: [
    "kenya take home pay calculator",
    "kenya salary after tax",
    "2026 kenya PAYE calculator",
    "KRA PAYE calculator",
    "kenya NSSF SHIF calculator",
    "affordable housing levy calculator",
    "kenya pension deduction calculator",
    "kenya insurance relief calculator",
    "kenya mortgage interest PAYE deduction",
    "kenya non cash benefits PAYE",
    "kenya car benefit PAYE tax",
  ],
  CO: [
    "colombia take home pay calculator",
    "colombia salary after tax",
    "2026 colombia tax calculator",
    "colombia UVT 2026 calculator",
    "colombia pension health contribution",
    "colombia voluntary pension AFC deduction",
    "colombia dependent deduction",
    "colombia electronic invoice deduction",
  ],
  BB: [
    "barbados take home pay calculator",
    "barbados salary after tax",
    "2026 barbados tax calculator",
    "barbados PAYE calculator",
    "barbados national insurance calculator",
    "barbados spouse allowance",
    "barbados pensioner allowance",
    "barbados medical expense deduction",
    "barbados charity deduction",
  ],
  BR: [
    "brazil take home pay calculator",
    "brazil salary after tax",
    "2026 brazil IRPF calculator",
    "brazil INSS calculator",
    "brazil 13th salary calculator",
    "decimo terceiro salario IRRF",
    "brazil PGBL deduction",
    "brazil dependent deduction",
    "brazil education medical deduction",
  ],
  PY: [
    "paraguay take home pay calculator",
    "paraguay salary after tax",
    "2026 paraguay tax calculator",
    "paraguay IRP calculator",
    "DNIT IRP RSP calculator",
    "paraguay IPS contribution calculator",
    "paraguay aguinaldo calculator",
    "aguinaldo IRP IPS Paraguay",
    "paraguay deductible expenses IRP",
    "salario neto paraguay",
  ],
  BZ: [
    "belize take home pay calculator",
    "belize salary after tax",
    "2026 belize tax calculator",
    "belize employee income tax calculator",
    "belize social security contribution calculator",
    "belize personal relief calculator",
    "belize charitable relief",
    "belize education relief",
    "belize SSB weekly insurable earnings",
    "BTS income tax calculator",
  ],
  PA: [
    "panama take home pay calculator",
    "panama salary after tax",
    "2026 panama tax calculator",
    "panama income tax calculator",
    "panama social security contribution",
    "panama educational insurance",
    "panama retirement fund deduction",
    "panama mortgage interest deduction",
    "panama education expense deduction",
  ],
  CR: [
    "costa rica take home pay calculator",
    "costa rica salary after tax",
    "2026 costa rica salary tax calculator",
    "costa rica CCSS calculator",
    "costa rica spouse tax credit",
    "costa rica child tax credit",
    "costa rica voluntary pension deduction",
    "costa rica aguinaldo calculator",
    "hacienda costa rica impuesto salario",
  ],
  EC: [
    "ecuador take home pay calculator",
    "ecuador salary after tax",
    "2026 ecuador income tax calculator",
    "SRI gastos personales 2026",
    "ecuador IESS contribution calculator",
    "ecuador personal expense rebate",
    "ecuador adulto mayor impuesto renta",
    "ecuador discapacidad impuesto renta exoneracion",
    "ecuador cargas familiares gastos personales",
    "ecuador impuesto renta calculadora",
  ],
  SV: [
    "el salvador take home pay calculator",
    "el salvador salary after tax",
    "2026 el salvador income tax calculator",
    "el salvador ISSS calculator",
    "el salvador AFP calculator",
    "el salvador voluntary AFP deduction",
    "el salvador medical education deduction",
  ],
  PE: [
    "peru take home pay calculator",
    "peru salary after tax",
    "2026 peru quinta categoria calculator",
    "SUNAT quinta categoria calculadora",
    "peru 7 UIT deduction",
    "peru 3 UIT deductible expenses",
    "peru pension contribution calculator",
    "peru AFP ONP calculator",
    "peru gratificacion salary calculator",
    "renta quinta categoria peru",
  ],
  GT: [
    "guatemala take home pay calculator",
    "guatemala salary after tax",
    "2026 guatemala ISR calculator",
    "guatemala rentas del trabajo calculator",
    "SAT Guatemala planilla IVA",
    "guatemala IGSS calculator",
    "guatemala life insurance deduction",
    "guatemala donations deduction",
  ],
  DO: [
    "dominican republic take home pay calculator",
    "dominican republic salary after tax",
    "2026 dominican republic ISR calculator",
    "DGII ISR asalariados 2026",
    "dominican republic AFP SFS calculator",
    "dominican republic TSS contribution salary",
    "dominican republic fringe benefits tax",
    "dominican republic christmas salary calculator",
    "salario de navidad impuesto renta dominicana",
    "dominican republic education expenses deduction",
    "Ley 179-09 gastos educativos",
  ],
  UY: [
    "uruguay take home pay calculator",
    "uruguay salary after tax",
    "2026 uruguay IRPF calculator",
    "uruguay BPS FONASA calculator",
    "uruguay child deduction IRPF",
    "uruguay rent credit IRPF",
    "uruguay mortgage deduction IRPF",
    "uruguay AFAP voluntary savings",
    "uruguay aguinaldo IRPF calculator",
  ],
  CL: [
    "chile take home pay calculator",
    "chile salary after tax",
    "2026 chile second category tax calculator",
    "chile AFP health unemployment calculator",
    "chile APV deduction calculator",
    "chile APV regime A fiscal bonus",
    "chile APV regime B deduction",
    "chile Isapre additional premium calculator",
    "chile seguro cesantia contrato indefinido",
    "SII impuesto segunda categoria 2026",
  ],
  RO: [
    "romania take home pay calculator",
    "romania salary after tax",
    "2026 romania tax calculator",
    "romania CAS CASS calculator",
    "romania voluntary pension deduction",
    "romania voluntary health insurance deduction",
    "romania private healthcare subscription deduction",
    "romania personal deduction calculator",
    "romania deducere personala calculator",
    "romania under 26 deduction",
    "romania child school deduction",
  ],
  AD: [
    "andorra take home pay calculator",
    "andorra salary after tax",
    "2026 andorra IRPF calculator",
    "andorra CASS salary calculator",
    "andorra pension deduction",
    "andorra family deduction calculator",
    "andorra mortgage tax relief",
  ],
  AL: [
    "albania take home pay calculator",
    "albania salary after tax",
    "2026 albania tax calculator",
    "albania social insurance calculator",
    "albania voluntary pension deduction",
    "albania child deduction calculator",
    "albania education expense deduction",
    "albania DIVA deduction calculator",
    "albania benefits in kind tax",
    "albania payroll allowance calculator",
  ],
  BA: [
    "bosnia take home pay calculator",
    "bosnia and herzegovina salary after tax",
    "2026 bosnia payroll calculator",
    "federation bih income tax calculator",
    "republika srpska salary tax calculator",
    "brcko district salary calculator",
    "bosnia dependent allowance",
    "bosnia mortgage interest deduction",
    "bosnia life insurance deduction",
  ],
  BG: [
    "bulgaria take home pay calculator",
    "bulgaria salary after tax",
    "2026 bulgaria tax calculator",
    "bulgaria child tax relief",
    "bulgaria disability tax relief",
    "bulgaria voluntary pension tax relief",
    "bulgaria life insurance tax relief",
    "bulgaria donation tax relief",
    "bulgaria social insurance calculator",
  ],
  BH: [
    "bahrain take home pay calculator",
    "bahrain salary after tax",
    "2026 bahrain payroll calculator",
    "bahrain no personal income tax",
    "bahrain SIO contribution calculator",
    "bahrain SIO wage cap",
    "bahrain SIO basic wage allowances",
    "bahrain unemployment insurance employee",
    "bahrain expatriate salary calculator",
    "bahraini employee pension contribution",
  ],
  BS: [
    "bahamas take home pay calculator",
    "bahamas salary after tax",
    "2026 bahamas payroll calculator",
    "bahamas national insurance calculator",
    "bahamas NIB employee contribution",
    "bahamas weekly insurable wage ceiling",
    "bahamas tips gratuities NIB",
    "bahamas retirement benefit NIB category",
    "bahamas no personal income tax",
    "bahamas age 65 NIB rate",
  ],
  CH: [
    "switzerland take home pay calculator",
    "switzerland salary after tax",
    "2026 switzerland tax calculator",
    "zurich salary tax calculator",
    "swiss pillar 3a deduction",
    "switzerland child deduction calculator",
    "zurich childcare deduction calculator",
    "swiss health insurance premium deduction",
  ],
  CW: [
    "curacao take home pay calculator",
    "curacao salary after tax",
    "2026 curacao tax calculator",
    "curacao AOV AWW calculator",
    "curacao provident fund deduction",
    "curacao child allowance wage tax",
    "curacao elderly allowance",
    "curacao single earner allowance",
  ],
  EE: [
    "estonia take home pay calculator",
    "estonia salary after tax",
    "2026 estonia tax calculator",
    "estonia second pillar pension",
    "estonia third pillar deduction",
    "estonia pensionable age basic exemption",
  ],
  EG: [
    "egypt take home pay calculator",
    "egypt salary after tax",
    "2026 egypt salary tax calculator",
    "egypt social insurance calculator",
    "egypt NOSI salary cap 2026",
    "egypt taxable employment benefits",
    "egypt private pension insurance deduction",
    "egypt salary tax brackets",
    "egypt employee social insurance contribution",
  ],
  HR: [
    "croatia take home pay calculator",
    "croatia salary after tax",
    "2026 croatia payroll calculator",
    "croatia local income tax calculator",
    "croatia pension contribution calculator",
    "croatia benefits in kind payroll calculator",
    "croatia digital nomad tax exemption",
    "croatia youth tax relief calculator",
    "croatia returnee tax relief calculator",
  ],
  HU: [
    "hungary take home pay calculator",
    "hungary salary after tax",
    "2026 hungary tax calculator",
    "hungary family tax allowance",
    "hungary family contribution allowance",
    "hungary under 25 tax allowance",
    "hungary mothers tax exemption",
    "hungary first marriage allowance",
    "hungary personal allowance",
    "hungary voluntary pension tax credit",
  ],
  IL: [
    "israel take home pay calculator",
    "israel salary after tax",
    "2026 israel tax calculator",
    "israel credit points calculator",
    "israel national insurance salary",
    "israel study fund calculator",
    "keren hishtalmut salary calculator",
  ],
  JO: [
    "jordan take home pay calculator",
    "jordan salary after tax",
    "2026 jordan income tax calculator",
    "jordan social security salary calculator",
    "jordan charity donation deduction",
    "jordan personal expense exemption",
  ],
  LT: [
    "lithuania take home pay calculator",
    "lithuania salary after tax",
    "2026 lithuania tax calculator",
    "lithuania NPD calculator",
    "lithuania disability NPD calculator",
    "lithuania second pillar pension",
    "lithuania article 21 deductions",
    "lithuania pension contribution deduction",
    "lithuania life insurance relief",
    "lithuania study expense deduction",
  ],
  LU: [
    "luxembourg take home pay calculator",
    "luxembourg salary after tax",
    "2026 luxembourg tax calculator",
    "luxembourg tax class calculator",
    "luxembourg class 1 class 1a class 2 salary calculator",
    "luxembourg single parent tax credit",
    "luxembourg CIM calculator",
    "luxembourg private pension deduction",
  ],
  LV: [
    "latvia take home pay calculator",
    "latvia salary after tax",
    "2026 latvia tax calculator",
    "latvia dependant allowance",
    "latvia pensioner non-taxable minimum",
    "latvia eligible expenses deduction",
  ],
  MA: [
    "morocco take home pay calculator",
    "morocco salary after tax",
    "2026 morocco tax calculator",
    "morocco CNSS AMO calculator",
    "morocco first employment income tax exemption",
    "morocco pension insurance deduction",
    "morocco family charge tax reduction",
    "morocco mortgage interest deduction",
    "morocco charitable contributions deduction",
  ],
  MT: [
    "malta take home pay calculator",
    "malta salary after tax",
    "2026 malta tax calculator",
    "malta class 1 ssc calculator",
    "malta nomad residence permit tax",
    "malta authorised work 10 percent tax",
    "malta highly skilled individuals 15 percent tax",
    "malta pension tax credit",
  ],
  MU: [
    "mauritius take home pay calculator",
    "mauritius salary after tax",
    "2026 mauritius tax calculator",
    "MRA PAYE calculator",
    "mauritius dependent deduction",
    "mauritius tertiary education deduction",
    "mauritius carer wage deduction",
  ],
  PL: [
    "poland take home pay calculator",
    "poland salary after tax",
    "2026 poland tax calculator",
    "poland child tax relief",
    "poland IKZE deduction",
    "poland PIT-0 calculator",
    "poland under 26 tax relief",
    "poland return relief calculator",
    "poland family 4 plus relief",
    "poland donation deduction PIT/O",
    "poland internet relief deduction",
  ],
  ME: [
    "montenegro take home pay calculator",
    "montenegro salary after tax",
    "2026 montenegro payroll calculator",
    "montenegro digital nomad tax exemption",
    "montenegro municipal surtax salary",
    "montenegro benefits in kind tax",
    "montenegro pension unemployment contribution",
  ],
  RS: [
    "serbia take home pay calculator",
    "serbia salary after tax",
    "2026 serbia salary tax calculator",
    "serbia social contributions calculator",
    "serbia payroll calculator",
    "serbia annual personal income tax calculator",
    "serbia under 40 tax relief",
    "serbia newly settled taxpayer relief",
    "serbia alternative investment fund tax credit",
    "serbia taxable fringe benefits salary",
  ],
  SA: [
    "saudi arabia take home pay calculator",
    "saudi salary after tax",
    "saudi gosi calculator",
    "saudi new gosi system calculator",
    "gosi contributory wage calculator",
    "saned employee contribution",
    "saudi expat salary calculator",
    "saudi GOSI housing allowance",
    "saudi basic wage GOSI calculator",
  ],
  RW: [
    "rwanda take home pay calculator",
    "rwanda salary after tax",
    "2026 rwanda PAYE calculator",
    "rwanda RSSB calculator",
    "rwanda CBHI salary contribution",
    "rwanda rssb medical scheme contribution",
    "rwanda voluntary pension contribution",
    "rwanda benefits in kind PAYE",
    "rwanda housing benefit tax",
  ],
  SC: [
    "seychelles take home pay calculator",
    "seychelles salary after tax",
    "2026 seychelles income tax calculator",
    "seychelles non citizen employment tax",
    "seychelles specific project tax",
    "seychelles stevedore tax",
    "seychelles pension fund contribution",
    "seychelles SPF voluntary contribution",
    "seychelles non monetary benefits tax",
    "seychelles SRC salary calculator",
  ],
  SI: [
    "slovenia take home pay calculator",
    "slovenia salary after tax",
    "2026 slovenia tax calculator",
    "slovenia social security calculator",
    "slovenia supplementary pension deduction",
    "slovenia dependent child allowance",
    "slovenia young worker allowance",
    "slovenia disability allowance",
    "slovenia meal reimbursement tax",
    "slovenia transport reimbursement",
    "slovenia regres holiday allowance",
  ],
  TR: [
    "turkey take home pay calculator",
    "turkey salary after tax",
    "2026 turkey income tax calculator",
    "turkey SSI salary calculator",
    "turkey disability allowance deduction",
    "turkey stamp tax salary calculator",
    "turkey minimum wage exemption",
    "turkey union dues deduction",
    "turkey education health expense deduction",
    "turkey donation relief calculator",
  ],
};


// Country-specific header descriptions
const COUNTRY_HEADER_INFO: Partial<Record<
  CountryCode,
  { tagline: string; details: string }
>> = {
  US: {
    tagline:
      "Calculate your actual salary after taxes for all 50 US states + D.C.",
    details:
      "Federal & state taxes, Social Security, Medicare, 401(k), HSA, IRA",
  },
  CA: {
    tagline: "Calculate your actual salary after taxes in Canada.",
    details:
      "Federal and provincial or territorial income tax, taxable non-cash benefits, CPP/CPP2 or Quebec QPP/QPP2, EI, QPIP, RRSP, FHSA, RPP, union dues, childcare, family credits, and charitable donation credits",
  },
  MX: {
    tagline: "Calculate your actual salary after taxes in Mexico.",
    details:
      "ISR, employee IMSS, employment subsidy, aguinaldo/vacation/PTU exemptions, state context, and voluntary retirement savings",
  },
  AU: {
    tagline: "Calculate your actual salary after taxes in Australia.",
    details:
      "Income tax (Stage 3 cuts), LITO, Medicare levy, Medicare levy surcharge, Division 293 tax, employer Super Guarantee, concessional super, work-related deductions, and DGR gifts",
  },
  NZ: {
    tagline: "Calculate your actual salary after taxes in New Zealand.",
    details:
      "PAYE income tax, ACC earners levy, student loans, KiwiSaver, IETC, and payroll giving donation credits",
  },
  OM: {
    tagline: "Calculate your actual salary after payroll deductions in Oman.",
    details:
      "0% 2026 personal income tax, expatriate or Omani worker mode, selected monthly SPF insured wage, old-age/disability/death insurance, employment security contribution, employer provident-scheme context, and optional SPF savings",
  },
  NL: {
    tagline: "Calculate your actual salary after taxes in the Netherlands.",
    details:
      "Income tax, national insurance, employee pension premium, lijfrente jaarruimte and reserveringsruimte, 30% ruling salary norms, general and labour tax credits, and IACK",
  },
  PT: {
    tagline: "Calculate your actual salary after taxes in Portugal.",
    details:
      "IRS income tax, Social Security, IRS Jovem, NHR 2.0, PPR tax credits, dependent deductions, and solidarity surcharge",
  },
  SG: {
    tagline: "Calculate your actual salary after taxes in Singapore.",
    details:
      "Income tax, age-based CPF, SRS, CPF top-ups, family reliefs, caregiver and disability reliefs, life insurance, donation deductions, NSman relief, and Parenthood Tax Rebate",
  },
  KR: {
    tagline: "Calculate your actual salary after taxes in South Korea.",
    details:
      "Income tax, local tax, foreign employee flat-tax election, four major insurance, dependants, child deductions, non-taxable allowances, pension/IRP, insurance, medical, education, donation, and rent credits",
  },
  KW: {
    tagline: "Calculate your actual salary after payroll deductions in Kuwait.",
    details:
      "0% personal income tax, expatriate or Kuwaiti worker mode, PIFSS basic and supplementary salary bases, pension-increase contribution, private/oil unemployment insurance, and conditional financial-remuneration contribution",
  },
  TH: {
    tagline: "Calculate your actual salary after taxes in Thailand.",
    details:
      "Personal income tax (0-35% progressive), Social Security Fund (5%), Provident Fund, RMF, SSF, ESG funds, allowances & deductions",
  },
  HK: {
    tagline: "Calculate your actual salary after taxes in Hong Kong.",
    details:
      "Salaries tax, MPF, employer-provided housing rental value, one-off tax reduction, resident allowances, MPF TVC/QDAP, VHIS, assisted reproductive services, charitable donations, and deductible expenses",
  },
  ID: {
    tagline: "Calculate your actual salary after taxes in Indonesia.",
    details:
      "PPh 21 income tax, BPJS Kesehatan/JHT/JP, PTKP family status, DPLK pension, and approved zakat deductions",
  },
  MY: {
    tagline: "Calculate your actual salary after taxes in Malaysia.",
    details:
      "Individual income tax, EPF/KWSP, SOCSO, EIS, PRS, voluntary EPF, YA 2025 resident reliefs, approved donation deductions, zakat/fitrah, and resident tax rebates",
  },
  TW: {
    tagline: "Calculate your actual salary after taxes in Taiwan.",
    details:
      "Resident progressive tax, non-resident salary withholding, Labor Insurance, Employment Insurance, National Health Insurance, voluntary labor pension, exemptions, standard or itemized deductions, special deductions, basic living expense difference, and Employment Gold Card relief",
  },
  UK: {
    tagline: "Calculate your actual salary after taxes in the United Kingdom.",
    details:
      "Income Tax (Personal Allowance taper £100k+), taxable benefits in kind, Class 1 National Insurance, Scottish tax bands, student loans, Marriage Allowance, and pension tax relief",
  },
  DE: {
    tagline: "Calculate your actual salary after taxes in Germany.",
    details:
      "Income tax (Einkommensteuer §32a EStG, progressive 0-45%), Solidarity Surcharge (Solidaritätszuschlag 5.5%), Pension Insurance (9.3%), Health Insurance (7.3% + Zusatzbeitrag), Unemployment Insurance (1.3%), Long-term Care Insurance (1.8-2.4%)",
  },
  AE: {
    tagline: "Calculate your actual salary after deductions in the United Arab Emirates.",
    details:
      "0% personal income tax, monthly basic salary for ILOE premiums, GPSSA contribution account salary, UAE national pension, and GCC insurance extension contributions",
  },
  AM: {
    tagline: "Calculate your actual salary after taxes in Armenia.",
    details:
      "20% income tax, funded pension, stamp duty, 2026 medical insurance, mortgage-interest refunds, specialized tuition refunds, and SRC social-expense refunds",
  },
  CN: {
    tagline: "Calculate your actual salary after taxes in China.",
    details:
      "Individual Income Tax (IIT, 3-45%), taxable in-kind benefits, annual one-time bonus tax treatment, social insurance, housing fund (5-12%), special additional deductions or foreign individual allowance exemptions, individual pension, enterprise annuity, tax-preferred health insurance, and approved charity deductions",
  },
  CZ: {
    tagline: "Calculate your actual salary after taxes in Czechia.",
    details:
      "15%/23% income tax, taxable non-cash benefits, company-car private-use valuation, social security, health insurance, taxpayer, spouse, child, disability and ZTP/P credits, retirement products, and charitable gifts",
  },
  JP: {
    tagline: "Calculate your actual salary after taxes in Japan.",
    details:
      "Employment income deduction, 2025+ basic deduction, spouse/dependent deductions, iDeCo, life-insurance, earthquake-insurance and medical-expense deductions, national income tax, resident tax, and social insurance",
  },
  IN: {
    tagline: "Calculate your actual salary after taxes in India.",
    details:
      "New or old regime income tax, Section 87A rebate, surcharge, 4% cess, EPF, HRA exemption, professional tax, Section 80C, NPS 80CCD(1B), and Section 80D medical insurance",
  },
  PH: {
    tagline: "Calculate your actual salary after taxes in the Philippines.",
    details:
      "Compensation income tax, SSS, PhilHealth, Pag-IBIG, 13th month/other benefits exclusion, BIR RR 29-2025 de minimis benefits, and non-resident gross tax option",
  },
  VN: {
    tagline: "Calculate your actual salary after taxes in Vietnam.",
    details:
      "2026 PIT law, resident or non-resident tax, social insurance, health insurance, foreign-worker unemployment treatment, updated family deductions, voluntary pension, and approved charity or humanitarian deductions",
  },
  KH: {
    tagline: "Calculate your actual salary after taxes in Cambodia.",
    details:
      "GDT tax on salary, resident or non-resident treatment, spouse and child allowances, taxable fringe benefits, and NSSF employee contributions",
  },
  LK: {
    tagline: "Calculate your actual salary after taxes in Sri Lanka.",
    details:
      "APIT employment tables, employee EPF, employer EPF/ETF context, secondary employment, remote foreign-employer Table 08, lump sums, in-kind or non-cash benefits, Table 03 terminal benefits, solar-panel relief, and qualifying donations",
  },
  FR: {
    tagline: "Calculate your actual salary after taxes in France.",
    details:
      "French income tax, taxable benefits in kind, family quotient cap, decote, professional expenses, PER savings, donations, impatriate salary-premium regime, and modeled employee contributions",
  },
  GE: {
    tagline: "Calculate your actual salary or IE income after taxes in Georgia.",
    details:
      "20% employment income tax, funded pension, individual entrepreneur small business status at 1%/3%, and micro business status up to the official limit",
  },
  IT: {
    tagline: "Calculate your actual salary after taxes in Italy.",
    details:
      "IRPEF, employee INPS social security, taxable fringe benefits, impatriate-worker regime, employment and family credits, supplementary pension, and regional/municipal add-ons",
  },
  IE: {
    tagline: "Calculate your actual salary after taxes in Ireland.",
    details:
      "PAYE income tax, Class A PRSI, USC, taxable benefit-in-kind, SARP inbound assignee relief, pension relief, MyFutureFund, rent, health, and family credits",
  },
  IS: {
    tagline: "Calculate your actual salary after taxes in Iceland.",
    details:
      "Withholding tax brackets, personal tax credit, mandatory employee pension, private supplementary pension savings, and approved foreign expert relief",
  },
  NO: {
    tagline: "Calculate your actual salary after taxes in Norway.",
    details:
      "Ordinary income tax, bracket tax, National Insurance, IPS pension savings, union dues, childcare, commuting, debt interest, and PAYE for eligible foreign workers",
  },
  GR: {
    tagline: "Calculate your actual salary after taxes in Greece.",
    details:
      "Greek income tax, taxable benefits in kind, age and dependent-child rate adjustments, e-EFKA employee contributions, occupational pension deductions, and Article 5C new-tax-resident relief",
  },
  DK: {
    tagline: "Calculate your actual salary after taxes in Denmark.",
    details:
      "AM-bidrag, income tax, average municipal tax, taxable benefits in kind, employment/job allowances, pension deductions, union/A-kasse, commuting, household services, work expenses, and researcher/highly paid employee tax scheme",
  },
  FI: {
    tagline: "Calculate your actual salary after taxes in Finland.",
    details:
      "State tax, municipal proxy, taxable fringe benefits, age-sensitive employee pension/unemployment/health contributions, commuting deduction, unemployment fund fees, income-production expenses, household expense credit, voluntary pension/PS savings, and foreign key employee tax at source",
  },
  SE: {
    tagline: "Calculate your actual salary after taxes in Sweden.",
    details:
      "Municipal tax-rate input, state income tax, general pension contribution, private pension savings when no occupational pension exists, commuting and work-expense deductions, ROT/RUT and green-technology reductions, and expert tax relief",
  },
  ES: {
    tagline: "Calculate your actual salary after taxes in Spain.",
    details:
      "IRPF, IRNR, regional scales, employee Social Security, pension reductions, family minimums, and Article 93 / Beckham-law flat salary tax",
  },
  BM: {
    tagline: "Calculate your actual salary after payroll deductions in Bermuda.",
    details:
      "Employee payroll tax, taxable cash or in-kind benefits, employer-absorbed payroll-tax option, social insurance, occupational pension, and capped health-insurance deductions",
  },
  QA: {
    tagline: "Calculate your actual salary after payroll deductions in Qatar.",
    details:
      "0% employment income tax, expatriate no-deduction treatment, and Qatari/GCC employee social insurance on GRSIA basic salary, social allowance, and capped housing allowance components when selected",
  },
  AT: {
    tagline: "Calculate your actual salary after taxes in Austria.",
    details:
      "2026 wage tax, employee social insurance, 13th/14th salary special payments, taxable in-kind benefits, transport credits, Pendlerpauschale, Family Bonus Plus, family credits, and special expenses",
  },
  BE: {
    tagline: "Calculate your actual salary after taxes in Belgium.",
    details:
      "Federal personal income tax, employee social security, taxable benefits in kind, tax-free allowance, dependent children, pension savings, childcare and gift tax reductions, special inpatriate regime allowance, and municipal surcharge proxy",
  },
  CY: {
    tagline: "Calculate your actual salary after taxes in Cyprus.",
    details:
      "Income tax, Social Insurance, GHS, TD59 deductions, approved pension/provident and medical-fund savings, family reliefs, and Article 8 first-employment exemptions",
  },
  ZA: {
    tagline: "Calculate your actual salary after taxes in South Africa.",
    details:
      "SARS PAYE, taxable fringe benefits, UIF, retirement fund deductions, age rebates, medical tax credits, AMTC, and Section 18A donations",
  },
  KE: {
    tagline: "Calculate your actual salary after taxes in Kenya.",
    details:
      "KRA PAYE, taxable non-cash benefits, NSSF, SHIF, Affordable Housing Levy, registered pension, post-retirement medical fund, mortgage interest, insurance relief, and PWD exemption",
  },
  CO: {
    tagline: "Calculate your actual salary after taxes in Colombia.",
    details:
      "Resident income tax, health and pension contributions, solidarity fund, dependents, prepaid health, housing interest, voluntary pension/AFC, and e-invoice deductions",
  },
  BB: {
    tagline: "Calculate your actual salary after taxes in Barbados.",
    details:
      "BRA PIT, National Insurance, Resilience Fund, spouse and pensioner allowances, medical exams, union dues, charity, and renewable energy deductions",
  },
  BR: {
    tagline: "Calculate your actual salary after taxes in Brazil.",
    details:
      "Receita Federal IRPF, employee INSS, 13th salary IRRF, dependents, PGBL, education and medical deductions, and the simplified annual discount",
  },
  PY: {
    tagline: "Calculate your actual salary after taxes in Paraguay.",
    details:
      "DNIT IRP-RSP, IPS employee contributions, legal aguinaldo treatment, threshold logic, and documented personal and family expense deductions",
  },
  BZ: {
    tagline: "Calculate your actual salary after taxes in Belize.",
    details:
      "BTS employee income tax, personal relief amendments, SSB weekly contribution bands, age exceptions, charitable relief, and education relief",
  },
  PA: {
    tagline: "Calculate your actual salary after taxes in Panama.",
    details:
      "Panama-source salary tax, social security, educational insurance, married exemption, mortgage interest, education, medical, charity, and retirement deductions",
  },
  CR: {
    tagline: "Calculate your actual salary after taxes in Costa Rica.",
    details:
      "Hacienda salary brackets, CCSS employee contribution, legal aguinaldo, spouse and child credits, and voluntary complementary pension relief",
  },
  EC: {
    tagline: "Calculate your actual salary after taxes in Ecuador.",
    details:
      "SRI income tax, IESS employee contribution, older-adult or disability income exemptions, personal-expense rebate, family dependents, and disability/catastrophic-illness caps",
  },
  SV: {
    tagline: "Calculate your actual salary after taxes in El Salvador.",
    details:
      "Salary withholding table, ISSS, AFP, voluntary AFP, and annual medical and education deductions",
  },
  PE: {
    tagline: "Calculate your actual salary after taxes in Peru.",
    details:
      "SUNAT fifth-category tax, 2026 UIT, 7 UIT deduction, statutory gratifications, EsSalud/EPS bonus, ONP or AFP withholding, and additional 3 UIT deductible expenses",
  },
  GT: {
    tagline: "Calculate your actual salary after taxes in Guatemala.",
    details:
      "SAT ISR, IGSS, Q48,000 deduction, VAT invoice credit, verified donations, and death-risk life insurance premiums",
  },
  DO: {
    tagline: "Calculate your actual salary after taxes in the Dominican Republic.",
    details:
      "DGII ISR scale, SDSS coverage, monthly AFP/SFS contribution salary, TSS caps, legal salario de Navidad treatment, employee-taxable fringe benefits, and Law 179-09 education expenses",
  },
  UY: {
    tagline: "Calculate your actual salary after taxes in Uruguay.",
    details:
      "IRPF, BPS pension, FONASA, labor reconversion, sueldo anual complementario, child deduction bases, voluntary AFAP, and rent or mortgage credits",
  },
  CL: {
    tagline: "Calculate your actual salary after taxes in Chile.",
    details:
      "SII second-category tax, AFP pension, 7% health, additional Isapre premium, unemployment insurance, and APV regime A or B savings",
  },
  RO: {
    tagline: "Calculate your actual salary after taxes in Romania.",
    details:
      "Flat PIT, CAS, CASS, Article 77 personal deductions, voluntary pension, and voluntary health insurance/private healthcare deductions",
  },
  AD: {
    tagline: "Calculate your actual salary after taxes in Andorra.",
    details:
      "IRPF, CASS, employment expense deduction, family and disability relief, mortgage relief, and pension-plan deductions",
  },
  AL: {
    tagline: "Calculate your actual salary after taxes in Albania.",
    details:
      "Employment allowance treatment, taxable benefits in kind, income tax, social insurance, health insurance, DIVA child and education deductions, and voluntary pension deductions",
  },
  BA: {
    tagline: "Calculate your actual salary after taxes in Bosnia and Herzegovina.",
    details:
      "FBiH, Republika Srpska, and Brcko salary tax, employee contributions, dependent allowances, disability deductions, mortgage interest, insurance, education, and voluntary deductions",
  },
  BG: {
    tagline: "Calculate your actual salary after taxes in Bulgaria.",
    details:
      "Flat PIT, employee social and health insurance, child, disabled-child, personal disability, voluntary insurance, and donation relief",
  },
  BH: {
    tagline: "Calculate your actual salary after payroll deductions in Bahrain.",
    details:
      "0% personal income tax, expatriate or Bahraini worker mode, SIO basic wage and recurring allowance inputs, BHD 4,000 monthly contribution cap, unemployment insurance, and Bahraini pension insurance",
  },
  BS: {
    tagline: "Calculate your actual salary after payroll deductions in The Bahamas.",
    details:
      "0% personal income tax, National Insurance category, selected weekly NIB basic wage, formal tips or gratuities, BSD 810 weekly ceiling, standard or age-65-plus employee NIB rates, and employer-only Retirement Benefit or summer-employment categories",
  },
  CH: {
    tagline: "Calculate your Zurich benchmark salary after taxes in Switzerland.",
    details:
      "Federal/cantonal/communal income tax, AHV/IV/EO, ALV, accident insurance, BVG proxy, Pillar 3a, family, childcare, insurance, training, and donation deductions",
  },
  CW: {
    tagline: "Calculate your actual salary after taxes in Curacao.",
    details:
      "Resident or foreign-taxpayer wage tax, basic credit, single-earner, child and elderly allowances, AOV/AWW, BVZ, AVBZ, and provident-fund deduction",
  },
  EE: {
    tagline: "Calculate your actual salary after taxes in Estonia.",
    details:
      "Income tax, general or pensionable-age basic exemption, unemployment insurance, second-pillar rate, and third-pillar deduction",
  },
  EG: {
    tagline: "Calculate your actual salary after taxes in Egypt.",
    details:
      "Salary tax brackets, personal exemption, NOSI social-insurance coverage and monthly salary base, taxable employment benefits, and private pension or insurance deductions",
  },
  HR: {
    tagline: "Calculate your actual salary after taxes in Croatia.",
    details:
      "Employee pension contributions, taxable benefits in kind, local income-tax rates, youth and returnee reliefs, resident spouse and child allowances, employer health-insurance context, and a qualifying digital-nomad foreign-employer scenario",
  },
  HU: {
    tagline: "Calculate your actual salary after taxes in Hungary.",
    details:
      "Flat PIT, employee social security, mother and under-25 PIT base allowances, personal and first-marriage allowances, family allowances, and voluntary pension fund credit",
  },
  IL: {
    tagline: "Calculate your actual salary after taxes in Israel.",
    details:
      "Income tax, resident and additional credit points, National Insurance, health insurance, employee pension, and Keren Hishtalmut study fund contributions",
  },
  JO: {
    tagline: "Calculate your actual salary after taxes in Jordan.",
    details:
      "PIT, national contribution tax, Social Security, resident-dependant exemptions, personal expenses, and donation deductions",
  },
  LT: {
    tagline: "Calculate your actual salary after taxes in Lithuania.",
    details:
      "PIT brackets, ordinary or disability NPD, state social insurance, health insurance, optional second-pillar pension, and Article 21 pension, insurance, and study deductions",
  },
  LU: {
    tagline: "Calculate your actual salary after taxes in Luxembourg.",
    details:
      "Class 1/1a/2 tax tables, employment fund surcharge, employee credits, social security, child and age class selection, single-parent tax credit, and private pension",
  },
  LV: {
    tagline: "Calculate your actual salary after taxes in Latvia.",
    details:
      "PIT, general or pensioner non-taxable minimum, dependant allowance, social insurance, pension/life insurance, and eligible expenses",
  },
  MA: {
    tagline: "Calculate your actual salary after taxes in Morocco.",
    details:
      "Income tax, CNSS, AMO, contribution wage bases, professional expense deduction, family charge reductions, first-employment IR exemption, mortgage interest, charity, and pension insurance deduction",
  },
  MT: {
    tagline: "Calculate your actual salary after taxes in Malta.",
    details:
      "MTCA tax bands, Class 1 SSC, PRS and occupational pension credits, qualifying fee deductions, Nomad Residence Permit authorised-work scenarios, and the Highly Skilled Individuals 15% regime",
  },
  MU: {
    tagline: "Calculate your actual salary after taxes in Mauritius.",
    details:
      "MRA PAYE, CSG, dependents, pension, medical insurance, charity, school fees, tertiary education, carer wages, housing, and green reliefs",
  },
  PL: {
    tagline: "Calculate your actual salary after taxes in Poland.",
    details:
      "PIT, ZUS, health insurance, PIT-0 reliefs, PPK, child relief, standard employee costs, IKZE, PIT/O donations, and internet relief",
  },
  ME: {
    tagline: "Calculate your actual salary after taxes in Montenegro.",
    details:
      "Payroll PIT, taxable benefits in kind, pension and unemployment contributions, municipal surtax context, and digital-nomad foreign-source scenario",
  },
  RS: {
    tagline: "Calculate your actual salary after taxes in Serbia.",
    details:
      "Salary tax, taxable fringe benefits, non-taxable salary amount, newly settled taxpayer relief, pension, health, unemployment, and supplementary annual PIT options",
  },
  RW: {
    tagline: "Calculate your actual salary after taxes in Rwanda.",
    details:
      "PAYE, taxable benefits in kind, RSSB pension or voluntary member coverage, maternity contribution, RSSB medical scheme option, and CBHI",
  },
  SA: {
    tagline: "Calculate your actual salary after taxes in Saudi Arabia.",
    details:
      "0% personal income tax on employment earnings, expatriate or Saudi worker mode, existing-system and 2026 new-system Saudi GOSI annuities, SANED, and GOSI wage base from basic wage plus cash or in-kind housing allowance",
  },
  SC: {
    tagline: "Calculate your actual salary after taxes in Seychelles.",
    details:
      "SRC citizen, non-citizen, specific-project, or stevedore employment tax, Seychelles Pension Fund employee contribution, optional SPF voluntary salary deduction, and employer-only non-monetary benefits tax estimate",
  },
  SI: {
    tagline: "Calculate your actual salary after taxes in Slovenia.",
    details:
      "PIT, general and dependent allowances, social security, long-term care, compulsory health, supplementary pension, tax-exempt meal and commute reimbursements, and holiday allowance",
  },
  TR: {
    tagline: "Calculate your actual salary after taxes in Turkey.",
    details:
      "GIB wage tax brackets, SSI, unemployment insurance, stamp tax, disability allowance, insurance premiums, union dues, education/health expenses, and donation relief",
  },
};

function getGenericCountryDescription(country: CountryCode): string {
  const config = getCountryConfig(country);
  return `Free ${config.taxYear} take home pay calculator for ${config.name}. Calculate your estimated salary after income tax where applicable, statutory payroll contributions, and modeled deductions.`;
}

function getGenericCountryKeywords(country: CountryCode): string[] {
  const config = getCountryConfig(country);
  const countryName = config.name.toLowerCase();
  return [
    `${countryName} take home pay calculator`,
    `${countryName} salary after tax`,
    `${config.taxYear} ${countryName} tax calculator`,
    `${countryName} paycheck calculator`,
  ];
}

function getGenericCountryHeaderInfo(country: CountryCode): {
  tagline: string;
  details: string;
} {
  const config = getCountryConfig(country);
  return {
    tagline: `Calculate your actual salary after taxes in ${config.name}.`,
    details:
      "Income tax where applicable, statutory payroll contributions, and modeled deductions",
  };
}

export function getCountryDescription(country: CountryCode): string {
  return COUNTRY_DESCRIPTIONS[country] ?? getGenericCountryDescription(country);
}

export function getCountryKeywords(country: CountryCode): string[] {
  return COUNTRY_KEYWORDS[country] ?? getGenericCountryKeywords(country);
}

export function getCountryHeaderInfo(country: CountryCode): {
  tagline: string;
  details: string;
} {
  return COUNTRY_HEADER_INFO[country] ?? getGenericCountryHeaderInfo(country);
}

export { COUNTRY_DESCRIPTIONS, COUNTRY_KEYWORDS, COUNTRY_HEADER_INFO };
