// This file is auto-generated by scripts/generate-country-registries.mjs.
// Do not edit by hand.

import { AECalculator } from "./ae";
import { ATCalculator } from "./at";
import { AUCalculator } from "./au";
import { BECalculator } from "./be";
import { CACalculator } from "./ca";
import { CNCalculator } from "./cn";
import { CYCalculator } from "./cy";
import { CZCalculator } from "./cz";
import { DECalculator } from "./de";
import { DKCalculator } from "./dk";
import { ESCalculator } from "./es";
import { FICalculator } from "./fi";
import { FRCalculator } from "./fr";
import { GECalculator } from "./ge";
import { GRCalculator } from "./gr";
import { HKCalculator } from "./hk";
import { HRCalculator } from "./hr";
import { IDCalculator } from "./id";
import { IECalculator } from "./ie";
import { INCalculator } from "./in";
import { ISCalculator } from "./is";
import { ITCalculator } from "./it";
import { JPCalculator } from "./jp";
import { KRCalculator } from "./kr";
import { MTCalculator } from "./mt";
import { MXCalculator } from "./mx";
import { MYCalculator } from "./my";
import { NLCalculator } from "./nl";
import { NOCalculator } from "./no";
import { NZCalculator } from "./nz";
import { PHCalculator } from "./ph";
import { PTCalculator } from "./pt";
import { SECalculator } from "./se";
import { SGCalculator } from "./sg";
import { THCalculator } from "./th";
import { TWCalculator } from "./tw";
import { UKCalculator } from "./uk";
import { USCalculator } from "./us";
import { VNCalculator } from "./vn";
import type { CountryCalculator, CountryCode } from "./types";

export interface CountryRegistryEntry {
  code: CountryCode;
  calculator: CountryCalculator;
}

export const COUNTRY_REGISTRY: CountryRegistryEntry[] = [
  { code: AECalculator.countryCode, calculator: AECalculator },
  { code: ATCalculator.countryCode, calculator: ATCalculator },
  { code: AUCalculator.countryCode, calculator: AUCalculator },
  { code: BECalculator.countryCode, calculator: BECalculator },
  { code: CACalculator.countryCode, calculator: CACalculator },
  { code: CNCalculator.countryCode, calculator: CNCalculator },
  { code: CYCalculator.countryCode, calculator: CYCalculator },
  { code: CZCalculator.countryCode, calculator: CZCalculator },
  { code: DECalculator.countryCode, calculator: DECalculator },
  { code: DKCalculator.countryCode, calculator: DKCalculator },
  { code: ESCalculator.countryCode, calculator: ESCalculator },
  { code: FICalculator.countryCode, calculator: FICalculator },
  { code: FRCalculator.countryCode, calculator: FRCalculator },
  { code: GECalculator.countryCode, calculator: GECalculator },
  { code: GRCalculator.countryCode, calculator: GRCalculator },
  { code: HKCalculator.countryCode, calculator: HKCalculator },
  { code: HRCalculator.countryCode, calculator: HRCalculator },
  { code: IDCalculator.countryCode, calculator: IDCalculator },
  { code: IECalculator.countryCode, calculator: IECalculator },
  { code: INCalculator.countryCode, calculator: INCalculator },
  { code: ISCalculator.countryCode, calculator: ISCalculator },
  { code: ITCalculator.countryCode, calculator: ITCalculator },
  { code: JPCalculator.countryCode, calculator: JPCalculator },
  { code: KRCalculator.countryCode, calculator: KRCalculator },
  { code: MTCalculator.countryCode, calculator: MTCalculator },
  { code: MXCalculator.countryCode, calculator: MXCalculator },
  { code: MYCalculator.countryCode, calculator: MYCalculator },
  { code: NLCalculator.countryCode, calculator: NLCalculator },
  { code: NOCalculator.countryCode, calculator: NOCalculator },
  { code: NZCalculator.countryCode, calculator: NZCalculator },
  { code: PHCalculator.countryCode, calculator: PHCalculator },
  { code: PTCalculator.countryCode, calculator: PTCalculator },
  { code: SECalculator.countryCode, calculator: SECalculator },
  { code: SGCalculator.countryCode, calculator: SGCalculator },
  { code: THCalculator.countryCode, calculator: THCalculator },
  { code: TWCalculator.countryCode, calculator: TWCalculator },
  { code: UKCalculator.countryCode, calculator: UKCalculator },
  { code: USCalculator.countryCode, calculator: USCalculator },
  { code: VNCalculator.countryCode, calculator: VNCalculator },
].sort((a, b) => a.calculator.config.name.localeCompare(b.calculator.config.name));
