// This file is auto-generated by scripts/generate-country-registries.mjs.
// Do not edit by hand.

import type { CountryCode } from "@/lib/countries/types";
import { buildCountryComparison as AECountryComparisonAdapter } from "@/lib/countries/ae/compare";
import { buildCountryComparison as ARCountryComparisonAdapter } from "@/lib/countries/ar/compare";
import { buildCountryComparison as ATCountryComparisonAdapter } from "@/lib/countries/at/compare";
import { buildCountryComparison as BECountryComparisonAdapter } from "@/lib/countries/be/compare";
import { buildCountryComparison as BRCountryComparisonAdapter } from "@/lib/countries/br/compare";
import { buildCountryComparison as CACountryComparisonAdapter } from "@/lib/countries/ca/compare";
import { buildCountryComparison as CHCountryComparisonAdapter } from "@/lib/countries/ch/compare";
import { buildCountryComparison as CNCountryComparisonAdapter } from "@/lib/countries/cn/compare";
import { buildCountryComparison as CYCountryComparisonAdapter } from "@/lib/countries/cy/compare";
import { buildCountryComparison as CZCountryComparisonAdapter } from "@/lib/countries/cz/compare";
import { buildCountryComparison as DKCountryComparisonAdapter } from "@/lib/countries/dk/compare";
import { buildCountryComparison as EECountryComparisonAdapter } from "@/lib/countries/ee/compare";
import { buildCountryComparison as FICountryComparisonAdapter } from "@/lib/countries/fi/compare";
import { buildCountryComparison as FRCountryComparisonAdapter } from "@/lib/countries/fr/compare";
import { buildCountryComparison as GECountryComparisonAdapter } from "@/lib/countries/ge/compare";
import { buildCountryComparison as HRCountryComparisonAdapter } from "@/lib/countries/hr/compare";
import { buildCountryComparison as HUCountryComparisonAdapter } from "@/lib/countries/hu/compare";
import { buildCountryComparison as IECountryComparisonAdapter } from "@/lib/countries/ie/compare";
import { buildCountryComparison as ILCountryComparisonAdapter } from "@/lib/countries/il/compare";
import { buildCountryComparison as INCountryComparisonAdapter } from "@/lib/countries/in/compare";
import { buildCountryComparison as ISCountryComparisonAdapter } from "@/lib/countries/is/compare";
import { buildCountryComparison as ITCountryComparisonAdapter } from "@/lib/countries/it/compare";
import { buildCountryComparison as JPCountryComparisonAdapter } from "@/lib/countries/jp/compare";
import { buildCountryComparison as MTCountryComparisonAdapter } from "@/lib/countries/mt/compare";
import { buildCountryComparison as MXCountryComparisonAdapter } from "@/lib/countries/mx/compare";
import { buildCountryComparison as NOCountryComparisonAdapter } from "@/lib/countries/no/compare";
import { buildCountryComparison as NZCountryComparisonAdapter } from "@/lib/countries/nz/compare";
import { buildCountryComparison as PHCountryComparisonAdapter } from "@/lib/countries/ph/compare";
import { buildCountryComparison as PLCountryComparisonAdapter } from "@/lib/countries/pl/compare";
import { buildCountryComparison as QACountryComparisonAdapter } from "@/lib/countries/qa/compare";
import { buildCountryComparison as SACountryComparisonAdapter } from "@/lib/countries/sa/compare";
import { buildCountryComparison as SECountryComparisonAdapter } from "@/lib/countries/se/compare";
import { buildCountryComparison as TRCountryComparisonAdapter } from "@/lib/countries/tr/compare";
import { buildCountryComparison as VNCountryComparisonAdapter } from "@/lib/countries/vn/compare";
import { buildCountryComparison as ZACountryComparisonAdapter } from "@/lib/countries/za/compare";
import type { CountryComparisonAdapter } from "./use-country-comparison";

export const COUNTRY_COMPARISON_ADAPTERS: Partial<
  Record<CountryCode, CountryComparisonAdapter>
> = {
  AE: AECountryComparisonAdapter,
  AR: ARCountryComparisonAdapter,
  AT: ATCountryComparisonAdapter,
  BE: BECountryComparisonAdapter,
  BR: BRCountryComparisonAdapter,
  CA: CACountryComparisonAdapter,
  CH: CHCountryComparisonAdapter,
  CN: CNCountryComparisonAdapter,
  CY: CYCountryComparisonAdapter,
  CZ: CZCountryComparisonAdapter,
  DK: DKCountryComparisonAdapter,
  EE: EECountryComparisonAdapter,
  FI: FICountryComparisonAdapter,
  FR: FRCountryComparisonAdapter,
  GE: GECountryComparisonAdapter,
  HR: HRCountryComparisonAdapter,
  HU: HUCountryComparisonAdapter,
  IE: IECountryComparisonAdapter,
  IL: ILCountryComparisonAdapter,
  IN: INCountryComparisonAdapter,
  IS: ISCountryComparisonAdapter,
  IT: ITCountryComparisonAdapter,
  JP: JPCountryComparisonAdapter,
  MT: MTCountryComparisonAdapter,
  MX: MXCountryComparisonAdapter,
  NO: NOCountryComparisonAdapter,
  NZ: NZCountryComparisonAdapter,
  PH: PHCountryComparisonAdapter,
  PL: PLCountryComparisonAdapter,
  QA: QACountryComparisonAdapter,
  SA: SACountryComparisonAdapter,
  SE: SECountryComparisonAdapter,
  TR: TRCountryComparisonAdapter,
  VN: VNCountryComparisonAdapter,
  ZA: ZACountryComparisonAdapter,
};
