// This file is auto-generated by scripts/generate-country-registries.mjs.
// Do not edit by hand.

import type { CountryCode } from "@/lib/countries/types";
import { buildCountryComparison as AECountryComparisonAdapter } from "@/lib/countries/ae/compare";
import { buildCountryComparison as CYCountryComparisonAdapter } from "@/lib/countries/cy/compare";
import { buildCountryComparison as DKCountryComparisonAdapter } from "@/lib/countries/dk/compare";
import { buildCountryComparison as FICountryComparisonAdapter } from "@/lib/countries/fi/compare";
import { buildCountryComparison as GECountryComparisonAdapter } from "@/lib/countries/ge/compare";
import { buildCountryComparison as HRCountryComparisonAdapter } from "@/lib/countries/hr/compare";
import { buildCountryComparison as ISCountryComparisonAdapter } from "@/lib/countries/is/compare";
import { buildCountryComparison as MTCountryComparisonAdapter } from "@/lib/countries/mt/compare";
import { buildCountryComparison as NOCountryComparisonAdapter } from "@/lib/countries/no/compare";
import { buildCountryComparison as SECountryComparisonAdapter } from "@/lib/countries/se/compare";
import type { CountryComparisonAdapter } from "./use-country-comparison";

export const COUNTRY_COMPARISON_ADAPTERS: Partial<
  Record<CountryCode, CountryComparisonAdapter>
> = {
  AE: AECountryComparisonAdapter,
  CY: CYCountryComparisonAdapter,
  DK: DKCountryComparisonAdapter,
  FI: FICountryComparisonAdapter,
  GE: GECountryComparisonAdapter,
  HR: HRCountryComparisonAdapter,
  IS: ISCountryComparisonAdapter,
  MT: MTCountryComparisonAdapter,
  NO: NOCountryComparisonAdapter,
  SE: SECountryComparisonAdapter,
};
