export { VNCalculator, calculateVN } from "./calculator";
export { VN_CONFIG, VN_CURRENCY } from "./config";
export {
  calculateVNProgressiveTax,
  VN_DEPENDENT_DEDUCTION_ANNUAL,
  VN_DEPENDENT_DEDUCTION_MONTHLY,
  VN_NON_RESIDENT_EMPLOYMENT_TAX_RATE,
  VN_PERSONAL_DEDUCTION_ANNUAL,
  VN_PERSONAL_DEDUCTION_MONTHLY,
  VN_SOURCE_URLS,
  VN_SOCIAL_INSURANCE_2026,
  VN_TAX_BRACKETS_2026,
  VN_VOLUNTARY_PENSION_DEDUCTION_ANNUAL_CAP,
} from "./constants/tax-parameters-2026";
