export { JPCalculator, calculateJP } from "./calculator";
export { JP_CONFIG, JP_CURRENCY } from "./config";
export {
  calculateJPBasicDeduction,
  calculateJPDependentDeduction,
  calculateJPEmploymentIncomeDeduction,
  calculateJPIncomeAdjustmentDeduction,
  calculateJPProgressiveTax,
  calculateJPQualifiedDonationDeduction,
  calculateJPResidentTaxBasicDeduction,
  calculateJPSpouseDeduction,
  getJPMarginalIncomeTaxRate,
  getJPIdecoAnnualLimit,
  JP_DONATION_DEDUCTION_LIMITS,
  JP_IDECO_ANNUAL_LIMITS,
  JP_INCOME_TAX_DEPENDENT_DEDUCTIONS,
  JP_INCOME_TAX_SPOUSE_DEDUCTION,
  JP_RECONSTRUCTION_SURTAX_RATE,
  JP_RESIDENT_TAX_PER_CAPITA,
  JP_RESIDENT_TAX_BASIC_DEDUCTION,
  JP_RESIDENT_TAX_DEPENDENT_DEDUCTIONS,
  JP_RESIDENT_TAX_RATE,
  JP_RESIDENT_TAX_SPOUSE_DEDUCTION,
  JP_SOURCE_URLS,
  JP_SOCIAL_INSURANCE_2026,
  JP_TAX_BRACKETS_2026,
  JP_TAX_YEAR,
} from "./constants/tax-parameters-2026";
